### ISSUE TITLE
league/oauth2-client update to 2.4.0 have breaking changes

### ISSUE THREAD

**Issue by nucleargen** [ekapusta/oauth2-esia#1]
Get error after latest update `league/oauth2-client` from 2.3.1 to 2.4.0 (lib loaded from depencies).

```
Declaration of Ekapusta\OAuth2Esia\Provider\EsiaProvider::getResourceOwnerDetailsUrl() must be compatible with League\OAuth2\Client\Provider\AbstractProvider::getResourceOwnerDetailsUrl(League\OAuth2\Client\Token\AccessTokenInterface $token)
```

Please, update your composer.json dependencies or update code.

**Comment by garex** [comment]
Ok, plan here will be this:

[ ] Provide hotfix with locking to ^2.3
[ ] Make a major release with dep to ^2 and updating code

In the meantime you can manage this issue on your side by locking league/oauth2-client to ^2.3 version.

**Comment by nucleargen** [comment]
> 
> In the meantime you can manage this issue on your side by locking league/oauth2-client to ^2.3 version.

Already ;)

**Comment by garex** [comment]
fixed in 1.2

**Comment by shahruslan-m** [comment]
Библиотека league/oauth2-client опять обновилась, до 2.4.1. И в этом обновлении они сделали revert изменений, связанных с AccessTokenInterface, и  Ваша библиотека опять ошибку выдает ))

**Comment by garex** [comment]
![image](https://user-images.githubusercontent.com/77981/49154134-407f1580-f34a-11e8-9ee6-c096b6e6e2f8.png)

![image](https://user-images.githubusercontent.com/77981/49154228-76bc9500-f34a-11e8-81d2-7778b8b3ae10.png)

**Comment by garex** [comment]
How to correclty say "пиздец" in english? ))

**Comment by shahruslan-m** [comment]
:)))

**Comment by nucleargen** [comment]
таки "fucked up" :D

**Comment by garex** [comment]
fxd
