### ISSUE TITLE
Как конвертировать ключи (gost2012)

### ISSUE THREAD

**Issue by demoniz** [ekapusta/oauth2-esia#13]
Приветствую! 
Прошу помощи, подскажите как правильно конвертировать гостовский сертификат для работы с данным расширением и извлечь из него публичный ключ.
Используем докер контейнер https://github.com/rnixik/docker-openssl-gost/tree/master/php-fpm-gost

С тестовыми ключами и сертификатами которые предоставляются из коробки все работает как надо.

Пробуем использовать продуктивный сертификат, его через экспорт windows (мастер экспорта сертификатов) сохраняем в "Файлы X.509(.CER) в кодировке Base-64".

Далее извлекаем ключ с помощью команды:
`for CERT in *.cer; do openssl x509 -engine gost -noout -pubkey -in $CERT -out ${CERT%.*}.public.key; done
`
Указываем пути до файлов, пробуем пройти авторизацию и получаем
`Fatal error: Uncaught RuntimeException: Operation failed with code#3 as of: unable to load signing key file 140678649394304:error:0906D06C:PEM routines:PEM_read_bio:no start line:crypto/pem/pem_lib.c:691:Expecting: ANY PRIVATE KEY unable to write 'random state'`

Подскажите в чем может быть проблема.

**Comment by garex** [comment]
pem/der
__________________
Alexander Ustimenko
    +7 (952) 918-02-20


пн, 5 окт. 2020 г. в 21:30, demoniz <notifications@github.com>:

**Comment by demoniz** [comment]
Прошу прощения, не понял. DER на сколько я понимаю является двоичным форматом сертификата, а тут судя по примерам используются не двоичные.

**Comment by garex** [comment]
Вы судя по всему экспортируете в бинарном формате.

`man openssl x509`
__________________
Alexander Ustimenko
    +7 (952) 918-02-20


пн, 5 окт. 2020 г. в 21:39, demoniz <notifications@github.com>:

**Comment by demoniz** [comment]
Подскажите как надо? Имеем продовский сертификат в формате .sert с алгоритмом подписи ГОСТ 2012. Так же есть 6 ключей (header.key, masks.key, masks2.key, name.key, primary.key, primary2.key).  Какие дальнейшие действия должны быть?

**Comment by garex** [comment]
Ааа... Тогда вам сюда

https://github.com/garex/nodejs-gost-crypto
__________________
Alexander Ustimenko
    +7 (952) 918-02-20


пн, 5 окт. 2020 г. в 21:55, demoniz <notifications@github.com>:

**Comment by demoniz** [comment]
Если не сложно, подскажите как это использовать, node установлен

**Comment by garex** [comment]
Cами пробуйте, я уже давно не работал с этой штукой.
__________________
Alexander Ustimenko
    +7 (952) 918-02-20


пн, 5 окт. 2020 г. в 22:24, demoniz <notifications@github.com>:

**Comment by demoniz** [comment]
@garex подскажите, а вы проверяли работу в продакшене? У нас почему то постоянно вылезает ошибка "ESIA-007005: Система-клиент не имеет права запрашивать получение маркера доступа таким методом". Хотя тот же код отлично работает с вашими тестовыми данными. Ключи в итоге мы портировали с помощью покупной P12FromGostCSP в pfx. 

Далее конвертировали
# openssl pkcs12 -in p12.pfx -nokeys -out p12.crt
# openssl pkcs12 -in p12.pfx -nocerts -out p12.pem -nodes

Может быть конечно и клиент что то с настройкой напутал....

**Comment by garex** [comment]
Это скоупы. Вы хотите больше чем можно.

пт, 9 окт. 2020 г., 19:04 demoniz <notifications@github.com>:

**Comment by demoniz** [comment]
Я тоже так думал, но уже указаны только 2 'openid', 'fullname'

**Comment by garex** [comment]
Мб минком не включил систему? Или алгоритм не тот выбран.

пт, 9 окт. 2020 г., 19:07 demoniz <notifications@github.com>:

**Comment by demoniz** [comment]
Алгоритм стоит верный. А вот как проверить включил он ее или нет это вопрос....

**Comment by nucleargen** [comment]
включил = успешно закрыл запрос на подключение ИС к боевому контуру.

Вот так вот не надо: openid, fullname !
Надо вот тааак: fullname, id_doc (или просто fullname) 
Понятно?

**Comment by garex** [comment]
У нас вот так работает: `'defaultScopes' => ['openid', 'fullname', 'id_doc',]`

**Comment by demoniz** [comment]
@nucleargen когда проблема в scope он будет писать ESIA-007019 noGrants

**Comment by yatakrad** [comment]
@garex добрый день!  
Не подскажите , использую https://github.com/garex/nodejs-gost-crypto , создал папку с 6 файлами key которые мне выдали , далее запуск , чтобы преобразовать в pem и у меня выходит ошибка 
Error: Incorrect fp
    nodejs-gost-crypto-nodefy\lib\gostKeys.js:959:27м
    
    В чем может быть проблема ?
