### ISSUE TITLE
Ошибка при установке в проект с Laravel 8

### ISSUE THREAD

**Issue by M0nik** [ekapusta/oauth2-esia#14]
Здравствуйте!

Возникает ошибка при установке:

`
Problem 1
ekapusta/oauth2-esia[1.4, ..., 1.4.1] require ramsey/uuid ^3.0 -> found ramsey/uuid[3.0.0-alpha1, ..., 3.x-dev] but the package is fixed to 4.1.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
`
`
Root composer.json requires ekapusta/oauth2-esia ^1.4 -> satisfiable by ekapusta/oauth2-esia[1.4, 1.4.1].
`

Laravel требует ramsey/uuid ^4.0

У `thephpleague/oauth2-client` не вижу зависимости от ^3.0, только в `ekapusta/oauth2-esia`

Как смотрите на обновление зависимости `ramsey/uuid` до 4 версии?

**Comment by garex** [comment]
Лучше тогда сделать через две палки. Типа `^3.0 || ^4.0`  и т.д.

**Comment by M0nik** [comment]
Согласен.
Посмотрел где используется эта библиотека - в одном месте для генерации state запроса.
Стоит ли тянуть вообще эту зависимость? 
Конкретно для целей данной библиотеки вполне подойдет упрощенная генерация, например, [из WP](https://developer.wordpress.org/reference/functions/wp_generate_uuid4/).

**Comment by garex** [comment]
Тоже вариант. Пробуйте.

**Comment by garex** [comment]
С т.з. трудозатрат две палки проще. С т.з. чистоты зависимостей -- своя имплементашка. Пулреквестите, чтобы всё зелено было и тесты проходили. Мне пофиг как. Если своя имплементашка -- чтоб ковередж 100% остался.

**Comment by garex** [comment]
fixed in 1.4.2
