### ISSUE TITLE
Проблемы с работой по ГОСТ 3410

### ISSUE THREAD

**Issue by Andreyb2b** [ekapusta/oauth2-esia#2]
После входа пользователя в ЕСИА и ответа с авторизационным кодом в примере предлагается так создавать токен:
`$token = $provider->getAccessToken('authorization_code', ['code' => $_GET['code']]);`
В getAccessToken вызывается  createAccessToken  в котором создаётся объект класса 
`\Ekapusta\OAuth2Esia\Token\EsiaAccessToken`
В нём идёт вызов 
`$this->parsedToken->verify(new Sha256(), new Key(file_get_contents($publicKeyPath)))`
А в  \Lcobucci\JWT\Signer\Rsa\Sha256 прописана работа только с RSA 
`    
public function getAlgorithmId()
    {
        return 'RS256';
    }
`
У меня же подпись на ГОСТ сертификате и в результате получаю ошибку.

Также у вас во всех найденных мною примерах используется код 
`$token = $provider->getAccessToken('authorization_code', ['code' => $_GET['code']]);
$esiaPersonData = $provider->getResourceOwner($accessToken);`
Сначала определяется $token, а используется уже $accessToken. Поправьте.

**Comment by garex** [comment]
Доки поправил.

В токене так и д.б. -- там нет ГОСТа. См. документацию на госуслугах.

Госты и прочее уже в подписи/проверке подписи.

**Comment by garex** [comment]
See https://github.com/ekapusta/oauth2-esia/blob/621bc6138e7045b71d4eaeed465421f977a89d0c/README.md#which-signer-to-use

**Comment by Andreyb2b** [comment]
Если в \Lcobucci\JWT\Token захардкодить в констркторе
`$this->headers = ['alg' => 'RS256'];`
То всё дальше работает. Но туда с подписью по ГОСТ прилетает GOST3410 в качестве значения. Не очень понятно, отчего так и что с этим делать

**Comment by garex** [comment]
@Andreyb2b напишите тест, как повторить баг если это баг. На данный момент тесты с гост-подписью проходят. См. https://travis-ci.org/ekapusta/oauth2-esia

**Comment by BoShurik** [comment]
Подтверждаю. Access token приходит с `alg = GOST3410_2012_256`
В документации информация об RSA нет: https://digital.gov.ru/uploaded/presentations/esiametodicheskierekomendatsii269.pdf

> В.5 Сведения о структуре и проверке маркера доступа
> 1. Алгоритм шифрования (“alg”, стандартное обозначение); в настоящее время в ЕСИА поддерживается алгоритм электронной подписи ГОСТ Р 34.10-2012 (соответствует значение значению “GOST3410_2012_512”)
