### ISSUE TITLE
Документация

### ISSUE THREAD

**Issue by stovberpv** [ekapusta/oauth2-esia#20]
Спасибо за такой классный пакет, но мог бы ты немного дополнить документацию?
К примеру сейчас совершенно не понятно как работать с гостовским шифрованием.
В пакете несколько параметров влияние которых на работу пакета просто невозможно понять

- `remotePublicKey`
- `remoteCertificatePath`
- `signer`
- `remoteSigner`

Какой параметр в каком случае надо использовать, а какой наоборот не нужно, к примеру - для работы с гостовским шифрованием нужно указывать `remotePublicKey` или только `remoteCertificatePath`, или оба?
А какое назначение `remoteSigner`? Этот параметр надо указывать вместе с `signer` или только что-то одно? В тестах в параметр `signer`, при использовании докера, передается параметр строки `-engine gost`, а для `remoteSigner` - нет. Почему так и как правильно?
В доке подключается сертификат `key` - `esia.gost.prod.public.key`, а в тестах `esia.gost.prod.cert`.
Если в этом месте есть опечатка в доке то может и где-то в остальном описании тоже?

Пакет вроде классный, работа проведена колоссальная, а воспользоваться трудами не получается, т.к. не понятно как именно пользоваться.

**Comment by garex** [comment]
Нет, не мог бы.

Пробуйте иные решения, учите англицкий. В ридми всё разжёвано. Да и сами
параметры очевидны.

Основы криптографии я точно не буду описывать -- что такое наш приватный
ключ, публичный ключ удалённой системы и т.д.


__________________
Alexander Ustimenko
    +7 (952) 918-02-20


сб, 29 янв. 2022 г. в 01:26, Paul ***@***.***>:

**Comment by stovberpv** [comment]
Спасибо за совет, но с английским все в порядке, похоже проблемы только с вашим пафосом.
