### ISSUE TITLE
Can not read private key

### ISSUE THREAD

**Issue by PiVirus** [ekapusta/oauth2-esia#21]
Доброго времени коллеги! Есть такая проблема, всю голову сломал, перепробовал кучу способов и ничего не помогает. Не читает openssl_pkey_get_private зараза приватный ключ, возвращает постоянно false. В переменной  $keyContent сидит строка:  string(160) "-----BEGIN PRIVATE KEY----- ....  -----END PRIVATE KEY-----, но ни как не обрабатывается, прямо перед вызовом openssl_pkey_get_private проверил, что в переменной. Пробовал указывать .key, .pem, строка приходит но ни как не проходит. Пробовал на разных версиях php: 7.4 8.0 и везде одно и тоже. Что ему нужно? Сертификат и ключи выданы в 2021 году. Буду благодарен любой помощи и подсказке.

**Comment by garex** [comment]
Наверное ключ гостовый, а читаете её пхпой, у которой опенссл не в курсе
про гост.
__________________
Alexander Ustimenko
    +7 (952) 918-02-20


ср, 22 июн. 2022 г. в 18:15, PiVirus ***@***.***>:

**Comment by PiVirus** [comment]
Закрыл не специально. Да забыл добавить же что ключи от Крипто Про конвертированные, вытащены ключи разными способами в разных форматах. Что можно предпринять или мне не подходит данное решение? Я так понимаю, на данном этапе, указанный remoteSigner не влияет на результат

**Comment by garex** [comment]
Если ключи от криптопро, то 146% гостовые.

Из коробки никакой опенссл не умеет в гост. Ни обычный, ни тот, который в
пхп.

Настройте свою сборку опенссля и используйте сигнеры, которые через cli на
вашу сборку будут ходить.
__________________
Alexander Ustimenko
    +7 (952) 918-02-20


ср, 22 июн. 2022 г. в 19:54, PiVirus ***@***.***>:

**Comment by PiVirus** [comment]
Прочитав кучу мануалов, я так и поступил, только собрать свою сборку толком не вышло, нашел в сети готовую OpenSSL-1.1.1h_win32 с поддержкой gost engine. Вот на неё указал в пути 'remoteSigner' => new OpenSslCliJwtSigner(__DIR__.'/OpenSSL-1.1.1h_win32'). Наверное я делаю не правильно и так же не правильно интерпритирую мануалы, а может просто криворукий :( И в общем результат, не может прочитать приватный ключ.

**Comment by nucleargen** [comment]
бесплатный пакет от cryptopro для linux вам в помощь. Пишем свою обертку над консольной утилитой cryptcp и используем в качестве подписанта для есиа

**Comment by injitools** [comment]
> бесплатный пакет от cryptopro для linux вам в помощь. Пишем свою обертку над консольной утилитой cryptcp и используем в качестве подписанта для есиа

это где бесплатный раздают?

**Comment by Zegerfor** [comment]
@PiVirus смогли решить проблему? Как с вами связаться? У меня ровно такая же ситуация

**Comment by PiVirus** [comment]
> 

Напиши мне на почту postman@itcrafter.ru

**Comment by mihdan** [comment]
Аналогичная проблема
