### ISSUE TITLE
Преобразование 6 файлов  key в pem

### ISSUE THREAD

**Issue by yatakrad** [ekapusta/oauth2-esia#22]
Подскажите , использую https://github.com/garex/nodejs-gost-crypto , создал папку с 6 файлами key которые мне выдали , далее запуск
node bin/export-cryptopro-key.js -c ./keys > private-key.pem.
 , чтобы преобразовать в pem и у меня выходит ошибка
Error: Incorrect fp
nodejs-gost-crypto-nodefy\lib\gostKeys.js:959:27м

Из-за чего это происходит ?

**Comment by dimajolkin** [comment]
С этой либой вроде проблемы есть. Я пользуюсь
https://github.com/s-sokolko/export-cryptopro-cert-docker

**Comment by yatakrad** [comment]
@dimajolkin А не подскажете, этапы пожалуйста. 
Я сначала из 6 файлов делаю один .pem и у меня также был выдан .cer (вместе с 6 файлами) 
Далее , можно уже работать с этими файлами для получения client_secret ? Или надо делать еще какие то манипуляции? 

Также , КриптоПро он обязателен для использования ?

**Comment by dimajolkin** [comment]
@yatakrad Этого достаточно. Только не забываем что при этом openssl должен быть с поддержкой GOST

**Comment by yatakrad** [comment]
@dimajolkin Спасибо!  https://altlinux.pkgs.org/sisyphus/classic-x86_64/lua5.1-module-luaossl-20190731-alt1.x86_64.rpm.html  вот этот я так понимаю подойдет ? 

Также, я поставил образ на линуксе sudo docker pull sokolko/export-cryptopro-cert  - он закачался 
далее, надо запустить sudo docker run --rm -v $PWD:/data sokolko/export-cryptopro-cert CONTAINER.000 123

CONTAINER.000 - вот тут не понятно , написано что имя директории с контейнером (набор файлов key Крипто ПРО). Это просто путь ? или какой еще контейнер ? не очень понятно тут

**Comment by dimajolkin** [comment]
@yatakrad 
1. CONTAINER.000 - это папка где лежат твои 6 файлов (название можно любое) в твоём случае папка должна быть в /data/CONTAINER.000 

2. https://www.altlinux.org/%D0%93%D0%9E%D0%A1%D0%A2_%D0%B2_OpenSSL
Или через докер 
docker run --rm -i -v $(pwd):$(pwd) -v /tmp/tmp -w $(pwd) rnix/openssl-gost openssl

**Comment by yatakrad** [comment]
[docker@*** ]$ docker run --rm -v $PWD:/data sokolko/export-cryptopro-cert /data/d1f73ca5.000
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
ERROR: read header
Чет по всякому попробовал . Ошибка эта может быть связана из файлов в папке ? В интернете не нашел ничего такого по данной ошибке

**Comment by dimajolkin** [comment]
@yatakrad docker run --rm -v $PWD:/data sokolko/export-cryptopro-cert d1f73ca5.000
Так правильней будет
А так у вас какая-то ошибка с docker проверьте правильность установки, я видел что вы через sudo запускали его первый раз может с этим связано

**Comment by yatakrad** [comment]
@dimajolkin  Все получилось спасибо! И с криптопро и с данным контейнером. 

Не подскажете , может работали с криптоПро , при установки JCP jar в свой проект , можно просто добавить их в структуру проекта ? или там особая установка ? 
Не очень понятно , когда используешь графический jcp или контейнер , там явно указываешь на файлы , а вот через библиотеку java от криптопро , как указать  именно в коде

**Comment by yatakrad** [comment]
Спасибо за ответы! ) @dimajolkin
