### ISSUE TITLE
ESIA расшифровка JWT

### ISSUE THREAD

**Issue by yatakrad** [ekapusta/oauth2-esia#23]
JWT , который возвращает мне ESIA в поле code , расшифровывается только CryproPro ? Есть ли примеры или рекомендации , которые способны провалидировать этот JWT ? 

То есть при использовании фильтров (которые предоставляет spring) я укажу в них валидацию этих токенов , чтобы пользователь авторизовывался в приложении.

Не очень понимаю как осуществлять его проверку. Какой сертификат именно нужен , который будет это делать ?

**Comment by garex** [comment]
Это так то на пхп проект.

В яве у баунси касла вроде есть всё и ещё немного больше. JWT там вообще по
моему РСА или ГОСТ12 умеет. И не обязательно крпитопрой это.
__________________
Alexander Ustimenko
    +7 (952) 918-02-20


пт, 3 февр. 2023 г. в 14:43, Daniil ***@***.***>:

**Comment by yatakrad** [comment]
@garex  не подскажешь , чтобы получить маркер , нужно отправлять на след. URL:
https://esia-portal1.test.gosuslugi.ru/aas/oauth2/te   
и в body передавать параметры типа : 
{
"client_id":.. ,
"code":.. ,
"grant_type":.. ,
"client_secret":.. ,
"state":"5d77d9ac-5d55-494d-8a0c-1e5f021aa813",
"scope": "fullname",
"timestamp":"2023.02.16+17%3A18%3A07+%2B0400",
"token_type": "Bearer"
}

при отправке , у меня возникает ошибка :
{
    "error_description": "ESIA-007014: The request doesn`t contain the mandatory parameter [state, client_id].",
    "error": "invalid_request"
}

Хотя я все передал как в доке. В чем может быть проблема ?

**Comment by garex** [comment]
хз. метод не тот, параметр не тот, что-то не подписано.
