### ISSUE TITLE
Тестовый доступ

### ISSUE THREAD

**Issue by artur008** [ekapusta/oauth2-esia#4]
Скажите, пожалуйста, а как использовать тестовый сервер ЕСИА? Там нужны файлы cer и key, а также тестовые логин и пароль.
Если использовать неправильные cer и key, то, после авторизации выдаёт ошибку.

Тестовые же логин и пароль - такие:
EsiaTest001@yandex.ru, EsiaTest002@yandex.ru, и т.д. до EsiaTest016@yandex.ru,
а пароль везде 11111111. У логинов разные статусы.

Про cer и key - вопрос открыт.

**Comment by garex** [comment]
https://github.com/ekapusta/oauth2-esia/blob/b2526df428f664f760dd48271f7d4e182225c261/tests/Factory.php#L47:L52

https://github.com/ekapusta/oauth2-esia/blob/b2526df428f664f760dd48271f7d4e182225c261/.travis.yml#L12:L13

**Comment by artur008** [comment]
А в комплекте этих файлов нет.
Есть  esia.test.cer только, и тот без key

**Comment by garex** [comment]
https://github.com/ekapusta/oauth2-esia/blob/b2526df428f664f760dd48271f7d4e182225c261/resources/ekapusta.gost.test.cer
https://github.com/ekapusta/oauth2-esia/blob/b2526df428f664f760dd48271f7d4e182225c261/resources/ekapusta.gost.test.key

esia.test.cer -- это сертификат удалённой системы, а не ваш тестовы.

**Comment by artur008** [comment]
А можете ekapusta.rsa.test.cer и ekapusta.rsa.test.key выложить?

**Comment by garex** [comment]
У вас всё уже есть.

https://github.com/ekapusta/oauth2-esia/tree/b2526df428f664f760dd48271f7d4e182225c261/resources

**Comment by artur008** [comment]
`use Ekapusta\OAuth2Esia\Provider\EsiaProvider;
use Ekapusta\OAuth2Esia\Security\Signer\OpensslPkcs7;




$provider = new EsiaProvider([
    'clientId'      => 'XXXXXXX',
    'redirectUri'   => $redirectUri,
    'defaultScopes' => ['openid','fullname'],
// For work with test portal version
	'remoteUrl' => 'https://esia-portal1.test.gosuslugi.ru',
	'remoteCertificatePath' => EsiaProvider::RESOURCES.'esia.test.cer'
],
 [
 'signer' => new OpensslPkcs7("$pathToCerts/ekapusta.rsa.test.cer", "$pathToCerts/ekapusta.rsa.test.key")]
);


$authUrl = $provider->getAuthorizationUrl();

$_SESSION['oauth2.esia.state'] = $provider->getState();
header('Location: '.$authUrl);
exit;`

Делаю так. После авторизации все равно возвращает ошибку "Выполнение операции прервано из-за ошибки авторизации.". 

Пробовал сертификаты:

ekapusta.rsa.test.cer
ekapusta.rsa.test.key
и
another.rsa.test.cer
another.rsa.test.key

**Comment by garex** [comment]
Почему здесь работает?

https://travis-ci.org/ekapusta/oauth2-esia

**Comment by artur008** [comment]
Спасибо большое, разобрался!

**Comment by artur008** [comment]
Простите, ещё вопрос. resourceOwnerId - это же и есть ID пользователя в Госуслугах?

**Comment by garex** [comment]
@artur008 будьте авантюристом, исследуйте!

Я уже не помню что там есть что ))

**Comment by magedigital** [comment]
Скажите, пожалуйста, а я правильно понимаю, что сертификат 

EsiaProvider::RESOURCES.'esia.prod.cer' для рабочего режима тоже должен быть свой, отдельный.
Т.е. его нужно сформировать и в ЕСИА зарегистрировать предварительно?

**Comment by garex** [comment]
Нет. Это сертификат продавай удаленной системы. Он для всех один. Нужен
чтобы понять, что АПИ это именно АПИ, а не сер с горы.
__________________
Alexander Ustimenko
    +7 (952) 918-02-20


пт, 23 авг. 2019 г. в 13:35, magedigital <notifications@github.com>:
