### ISSUE TITLE
Работа с Крипто-Про сертификатами

### ISSUE THREAD

**Issue by noirwave** [ekapusta/oauth2-esia#5]
Подскажите, пожалуйста, как можно осуществить подпись сертификатами от Крипто-Про?
Имеем машину с установленными утилитами крипто-про и сертификатами.
Сертификат у них  - это один файл, а ключей закрытый - папка с шестью файлами .key
Мы их установили через утилиты криптопро, но как использовать это, какой Signer использовать - не совсем понятно.

**Comment by noirwave** [comment]
Ключи экспортировал в .pem, а сертификат надо экспортировать?
сейчас при openssl_x509_read возвращается ошибка
```
openssl_x509_read(file_get_contents(Yii::getAlias('@common/config/esia/client/cert2018.cer')));
```
```
openssl_x509_read(): supplied parameter cannot be coerced into an X509 certificate!
```
Файл существует и читается.
`php -i` Выводит
```
Hashing Engines => md2 md4 md5 sha1 sha224 sha256 sha384 sha512 ripemd128 ripemd160 ripemd256 ripemd320 whirlpool tiger128,3 tiger160,3 tiger192,3
 tiger128,4 tiger160,4 tiger192,4 snefru snefru256 gost gost-crypto adler32 crc32 crc32b fnv132 fnv1a32 fnv164 fnv1a64 joaat haval128,3 haval160,3
 haval192,3 haval224,3 haval256,3 haval128,4 haval160,4 haval192,4 haval224,4 haval256,4 haval128,5 haval160,5 haval192,5 haval224,5 haval256,5
```

**Comment by garex** [comment]
Сертификат в каком формате? der/pem? 

`cat common/config/esia/client/cert2018.cer | opessl asn1parse`

**Comment by noirwave** [comment]
Мы используем докер контейнер https://hub.docker.com/r/required/cryptopro
Но там нет команды openssl, поэтому там проверить пока не получится. Сейчас еще попробую другой контейнер поднять с openssl и гостами внутри.

Пока обычный openssl без госта выводит это:
```
cat cert2018.cer | openssl asn1parse
Error: offset too large
```

**Comment by noirwave** [comment]
попробовал еще пару аргументов
```
cat cert2018.cer | openssl asn1parse -inform der                                         
  0:d=0  hl=4 l=2296 cons: SEQUENCE                                                      
  4:d=1  hl=4 l=2215 cons: SEQUENCE                                                      
  8:d=2  hl=2 l=   3 cons: cont [ 0 ]                                                    
 10:d=3  hl=2 l=   1 prim: INTEGER           :02                                         
 13:d=2  hl=2 l=  16 prim: INTEGER           :01D471E6CEDC55300000623A03130002           
 31:d=2  hl=2 l=   8 cons: SEQUENCE                                                      
 33:d=3  hl=2 l=   6 prim: OBJECT            :GOST R 34.11-94 with GOST R 34.10-2001     
 41:d=2  hl=4 l= 332 cons: SEQUENCE                                                      
 45:d=3  hl=2 l=  24 cons: SET                                                           
 47:d=4  hl=2 l=  22 cons: SEQUENCE                                                      
 49:d=5  hl=2 l=   5 prim: OBJECT            :1.2.643.100.1                              
 56:d=5  hl=2 l=  13 prim: NUMERICSTRING     :1025203036506                              
 71:d=3  hl=2 l=  26 cons: SET                                                           
 73:d=4  hl=2 l=  24 cons: SEQUENCE                                                      
 75:d=5  hl=2 l=   8 prim: OBJECT            :1.2.643.3.131.1.1                          
 85:d=5  hl=2 l=  12 prim: NUMERICSTRING     :005260013152                               
 99:d=3  hl=2 l=  37 cons: SET                                                           
101:d=4  hl=2 l=  35 cons: SEQUENCE                                                      
103:d=5  hl=2 l=   3 prim: OBJECT            :streetAddress                              
108:d=5  hl=2 l=  28 prim: UTF8STRING        :ул.Ошарская, д.69                          
138:d=3  hl=2 l=  11 cons: SET                                                           
```

**Comment by noirwave** [comment]
Сконвертировал сертификат
```
openssl x509 -inform der -in certificate.cer -out certificate.pem
```
И вроде пока ошибок нет! Спасибо большое!

**Comment by Dkalugin** [comment]
noirwave 

> Ключи экспортировал в .pem, 

Добрый день!
Подскажите, пожалуйста, каким образом экспортировали ключи? Все ключи (все шесть *.key), или какой-то один?

**Comment by noirwave** [comment]
Dkalugin, экспортировали все ключи с помощью этой библиотеки https://github.com/garex/nodejs-gost-crypto

Но когда нам прислали более свежий сертификат и ключи, эта библиотека не помогла, выкидывало какую-то ошибку (не помню), которую не смогли поправить.

В итоге в требованиях появилось использование сертифицированных (квалифицированных?) подписчиков и мы воспользовались этим докер образом https://hub.docker.com/r/required/cryptopro
Импортировали туда ключ и написали небольшой АПИ по подписанию строки с помощью консольной утилиты.

**Comment by Dkalugin** [comment]
noirwave, спасибо. Буду искать и разбираться... Контейнер по ссылке, к сожалению, у нас не пройдет - у нас версия php 5.6.38
