### ISSUE TITLE
Ошибка "unauthorized_client" и реализация тестовой авторизации

### ISSUE THREAD

**Issue by Dunwolf** [ekapusta/oauth2-esia#7]
Здравствуйте.

Использую данный пакет для интеграции авторизации на ЕСИА через OAuth2.0.
Сейчас идёт разработка на тестовом сайте.
Установлены:
— собственно, ekapusta/oauth2-esia;
— openssl 1.1.1d (настроен на сервере; через php cli отрабатывает успешно);

Сначала попробовал ключи RSA — получил url.
Пробовал использовать этот адрес — ЕСИА возвращала ошибку «unauthorized_client».
Гуглил — попробовал перейти на ГОСТ ключи. Собственно, сейчас на этом остановился.
PHP не читает алгоритмы ГОСТ, и запускать получается только из cli. Вариант нерабочий. Поздно дошло, что нужно специально компилить PHP под это дело.

Возможно, стоит вернуться к истокам и использовать RSA. Там хотя бы url формировался.
Из методички ЕСИА не совсем понял: там сказано про поддержку ГОСТ алгоритмов, но ни слова про RSA. ЕСИА их корректно обрабатывает?

Вопросы:
1. Можно ли вообще использовать RSA для процесса авторизации? Здесь тогда сразу возникает вопрос, что за ошибка «unauthorized_client». Может быть, вы сталкивались.
2. Какое корректное заполнение полей в конструкторе? Из-за «unauthorized_client» для RSA (вроде работает «как-то») не могу понять, влияют ли на появление этой ошибки другие параметры или нет.

```
$provider = new EsiaProvider(
    [
        'clientId'      => 'TEST', // "Мненомика" в терминах ЕСИА
        'redirectUri'   => 'http://example.com/', // подставляю свой адрес, всё норм
        'defaultScopes' => 'openid',
        // Для работы с тестовой версией портала
        'remoteUrl' => 'https://esia-portal1.test.gosuslugi.ru',
        'remoteCertificatePath' => EsiaProvider::RESOURCES.'esia.test.cer',
    ],
    [
        'signer' => new OpensslPkcs7('certs/test.cer', 'certs/test.key')
        // вариант RSA
        // openssl req -x509 -outform pem -nodes -days 18250  -utf8 -subj "/C=RU/CN=Tester RSA"   -keyout ekapusta.rsa.test.key  -out ekapusta.rsa.test.cer  -newkey rsa:2048
        // вариант ГОСТ
        // openssl req -x509 -outform pem -nodes -days 18250  -utf8 -subj "/C=RU/CN=Tester GOST"  -keyout test.key -out test.cer -newkey GOST2012_512 -pkeyopt paramset:A -engine gost
    ]
);
```

— clientId для тестовой среды какой использовать? Уже клиента или что-то иное?
— remoteCertificatePath — пока не могу понять смысл параметра. Есть в пакете два ключа для прода и теста, но для чего они? Методичку излазил, но не понял.

Словом, нужно запустить успешно тестовую авторизацию малой кровью.

**Comment by garex** [comment]
> PHP не читает алгоритмы ГОСТ, и запускать получается только из cli. Вариант нерабочий. 
Вариант рабочий.

RSA для прода по-мойму нет. Читайте методичку, пытайте минкомсвязи.

> clientId

Тот который у вашей системы выдан минкосвязи.

> remoteCertificatePath

Это для проверки подлинности ответа сервера.

**Comment by Dunwolf** [comment]
> Это для проверки подлинности ответа сервера.

Т.е. в remoteCertificatePath можно использовать, входящие в пакет esia.prod.cer и esia.test.cer?

> Вариант рабочий.
Но ведь для этого нужно скомпилить PHP c ГОСТ алгоритмами?
Есть готовое решение для этого?

**Comment by garex** [comment]
> Т.е. в remoteCertificatePath можно использовать, входящие в пакет esia.prod.cer и esia.test.cer?
Нужно.

> Но ведь для этого нужно скомпилить PHP c ГОСТ алгоритмами?
Нет. См. внимательно на тесты -- в том числе и с гостами там есть.

**Comment by Dunwolf** [comment]
Спасибо за помощь. Буду разбираться дальше

**Comment by reposgit** [comment]
А с гостовским сертификатом и ключом полученными из lissi (в связке с crypto pro) это решение будет работать?

**Comment by garex** [comment]
> А с гостовским сертификатом и ключом полученными из lissi (в связке с crypto pro) это решение будет работать?

Ключ в каком формате?

**Comment by reposgit** [comment]
PEM
-----BEGIN ENCRYPTED PRIVATE KEY-----
*****
-----END ENCRYPTED PRIVATE KEY-----

**Comment by garex** [comment]
Должно вполне.

**Comment by reposgit** [comment]
Detached подпись правильная вроде, проверял загрузкой в crypto pro, хэш как у сертификата, ссылку редиректа формирует, ввожу тестовые учетные данные в есиа, возвращает вместо code ошибку ESIA-007005: Система-клиент не имеет права запрашивать получение маркера доступа таким методом

**Comment by reposgit** [comment]
А вы не могли бы помочь за оплату доделать это? использовали ваш пакет как наиболее подходящий для нашей системы, но что то с подписью я так понимаю

**Comment by garex** [comment]
в ближайшие полгода -- нет

проблема где-то в настройках вашей системы в еста а не в подписи
__________________
Alexander Ustimenko
    +7 (952) 918-02-20


ср, 8 апр. 2020 г. в 17:01, reposgit <notifications@github.com>:

**Comment by reposgit** [comment]
А на этапе получения code scope должны обязательно совпадать с зарегистрированными в заявке на подключение к ЕСИА?

**Comment by Lotarevivan** [comment]
Подскажите для тестовой среды используется сертификат который мы загружаем в тех портал есиа?
Или это только для продуктива. 
Минком связь должна какие-то учетные данные предоставить? 
Пытаюсь для тестовой среды подписывать тем сертификатом который загрузил на тех портал получаю ESIA-007005 unauthorized_client

**Comment by garex** [comment]
> Подскажите для тестовой среды используется сертификат который мы загружаем в тех портал есиа? Или это только для продуктива. Минком связь должна какие-то учетные данные предоставить? Пытаюсь для тестовой среды подписывать тем сертификатом который загрузил на тех портал получаю ESIA-007005 unauthorized_client

Нет. См. автотесты внимательно.

**Comment by KlinDev** [comment]
> Detached подпись правильная вроде, проверял загрузкой в crypto pro, хэш как у сертификата, ссылку редиректа формирует, ввожу тестовые учетные данные в есиа, возвращает вместо code ошибку ESIA-007005: Система-клиент не имеет права запрашивать получение маркера доступа таким методом. В логах ЕСИА Can't find certificate for client id [***] on state [] cert thumbPrint ***, вот в thumbprint хэш не как у сертификата

Столкнулись с идентичной ошибкой после авторизации в тестовой среде.  В ИС тех портала тестовой среды указали тот-же тестовый сертификат, который используем для генерации подписи для поля client_secret, мнемоники тоже совпадают. 

Подскажите, у вас получилось ее исправить и как?

**Comment by garex** [comment]
Я это не ресёчил. У нас на проде работает.

Скорее всего где-то не тот серт подпихивается. Или форматы ключей не те,
которые openssl понимает. Можете своего подписанта на базе cli от криптопро
сделать.
__________________
Alexander Ustimenko
    +7 (952) 918-02-20


ср, 16 мар. 2022 г. в 22:41, Klindev ***@***.***>:
