### ISSUE TITLE
ГОСТ 2012

### ISSUE THREAD

**Issue by skald** [ekapusta/oauth2-esia#9]
Александр, добрый день!

Пользуемся Вашей системой по авторизации через ЕСИА.
Столкнулись с проблемой, что ЕСИА перестала принимать старые ключи и требует ГОСТ 2012.
Мы обновили сертификаты и ключи до ГОСТ 2012 (GOST R 34.11-2012/256), но система авторизации не работает. 
По описанию в readme у Вас на гитхабе видим, что подержка планировалась.

Можете подсказать поддержка ГОСТ 2012 не реализована еще? Или всё должно работать и мы что-то неправильно делаем?

Спасибо

**Comment by garex** [comment]
https://github.com/ekapusta/oauth2-esia/blob/92a7956297fede0dd62cf3224c15f915bf2132df/resources/README.md ?

**Comment by garex** [comment]
Как именно "не работает"? Кто на что ругается?

**Comment by skald** [comment]
После авторизации через сервис ЕСИА получаем в ответ ошибку о том, что невозможно проверить токен: https://i.imgur.com/DPw1rOp.png

**Comment by nucleargen** [comment]
Два косвенных вопроса: 
- в есиа переключили интеграцию на ГОСТ2012?
- как именно используете новые сертификаты? (у нас проблема с переключением из-за того, что они в криптопро контейнерах с невозможностью вытащить приватные ключи для прямого использования)

**Comment by garex** [comment]
Эээ... Если у вас ключи внутри криптопро, то вообще ниче не должно работать.
__________________
Alexander Ustimenko
    +7 (952) 918-02-20


чт, 14 мая 2020 г. в 15:11, Alexey <notifications@github.com>:

**Comment by nucleargen** [comment]
мы пытались экспортировать приватные ключи разными способами для использования в OpenSSL, но не вышло :) сейчас приходится реализовывать прокладку между вашей библиотекой и криптой. Благо она нам ещё и для других целей нужна.

**Comment by skald** [comment]
1. Собрали openssl с поддержкой GOST сертификатов:
openssl ciphers|tr ':' '\n'|grep GOST
GOST2012-GOST8912-GOST8912
GOST2001-GOST89-GOST89

2. Для подписи используем OpensslCli, указав путь к openssl в параметре toolpath.

3. openssl asn1parse -i -in private.key возвращает:
https://i.imgur.com/RqRZaGb.png

**Comment by skald** [comment]
В ЕСИА переключили да. https://gyazo.com/d9743d133dcb42a62a29d0fa0c2d38b8

**Comment by garex** [comment]
Так если вы не экспортировали, то вам нет смысла использовать OpensslCli!

Как эт вы пытаетесь не опенссльные ключи через него прогнать?

Пишите свой какой-нить CryptoProCli , чтоб он всё умел и потом присылайте
пулреквест.
__________________
Alexander Ustimenko
    +7 (952) 918-02-20


чт, 14 мая 2020 г. в 15:21, Vlad <notifications@github.com>:

**Comment by nucleargen** [comment]
Продолжая тему:
мы запилили свою апи-обертку над криптопро, сделали свой Signer, указали сертификат ГОСТ2012 в ЕСИА, и уткнулись в ту же проблему верификации токена:
```
Access token can not be verified: array (
  \'access_token\' => \'blabla\',
  \'refresh_token\' => \'blabla\',
  \'state\' => \'blabla\',
  \'token_type\' => \'Bearer\',
  \'expires_in\' => 3600,
)
#0 vendor/ekapusta/oauth2-esia/src/Provider/EsiaProvider.php(198): Ekapusta\\OAuth2Esia\\Token\\EsiaAccessToken->__construct(Array, \'/var/www/vendor...\')
#1 vendor/league/oauth2-client/src/Provider/AbstractProvider.php(536): Ekapusta\\OAuth2Esia\\Provider\\EsiaProvider->createAccessToken(Array, Object(League\\OAuth2\\Client\\Grant\\AuthorizationCode))
#2 vendor/ekapusta/oauth2-esia/src/EsiaService.php(51): League\\OAuth2\\Client\\Provider\\AbstractProvider->getAccessToken(Object(League\\OAuth2\\Client\\Grant\\AuthorizationCode), Array)
#3 OAuthEsia.php(71): Ekapusta\\OAuth2Esia\\EsiaService->getResourceOwner(\'...\', \'...\', \'...\')
#4 {main}'
```

**Comment by plutonio00** [comment]
Та же проблема. ЕСИА работает, однако в файле vendor/lcobucci/jwt/src/Token.php проверка
```
if ($this->headers['alg'] !== $signer->getAlgorithmId()) {
       return false;
}
```
возвращает false, поскольку $this->headers['alg'] имеет значение GOST3410_2012_256, тогда как $signer->getAlgorithmId() - ES256. Даже если отключить эту проверку на этом проблемы не кончаются. Что можно сделать в данной ситуации?

**Comment by plutonio00** [comment]
Кстати этот вопрос уже задавался
https://github.com/ekapusta/oauth2-esia/issues/2
Верификация токена проходит только в тестовой среде ЕСИА, но не в продовой.

**Comment by nucleargen** [comment]
Нам на данный момент пришлось решить проблему проверки токена полной подменой EsiaAccessToken на свою реализацию с удалением следующих проверок:
```
        if (!$this->parsedToken->validate(new ValidationData())) {
            throw new InvalidArgumentException('Access token is invalid: '.var_export($options, true));
        }

        if (null == $publicKeyPath) {
            return;
        }

        if (!$this->parsedToken->verify(new Sha256(), new Key(file_get_contents($publicKeyPath)))) {
            throw new InvalidArgumentException('Access token can not be verified: '.var_export($options, true));
        }
```
Сейчас пытаемся реализовать свою верификацию по ГОСТ2012 через наш крипто-сервис, дальше займемся валидацией. Может у кого уже получилось ? А то ЕСИА в октябре вообще RSA отрубает :) (на бою мы уже используем ГОСТ)

**Comment by garex** [comment]
Закиньте пул-реквест что ли?
__________________
Alexander Ustimenko
    +7 (952) 918-02-20


ср, 23 сент. 2020 г. в 14:03, Alexey <notifications@github.com>:

**Comment by lemanko** [comment]
Тоже стала выскакивать ошибка "Access token can not be verified" хотя на прошлой неделе все работало корректно. Код с прошлой недели даже ни кто и не трогал...

**Comment by garex** [comment]
Мб вас зафорсили с рса на ГОСТ?

пн, 28 сент. 2020 г., 11:05 MediaTen <notifications@github.com>:

**Comment by lemanko** [comment]
Мы пока для теста пользовались вашими ключами
ekapusta.rsa.test.cer
ekapusta.rsa.test.key

**Comment by garex** [comment]
Ааа... И на нашу тестовую систему? Я её переключил на ГОСТ просто.

пн, 28 сент. 2020 г., 11:38 MediaTen <notifications@github.com>:

**Comment by lemanko** [comment]
Да, и ваш мнемоник. Тогда понятно в чем дело. А ключи для GOST 2012 для теста так же доступны в репозитории?

**Comment by garex** [comment]
Я как веточку залью, всё заработает. Пока девелоп и мастер сломаты.
__________________
Alexander Ustimenko
    +7 (952) 918-02-20


пн, 28 сент. 2020 г. в 12:32, MediaTen <notifications@github.com>:

**Comment by lemanko** [comment]
Верно мы понимаем что на данный момент работа с GOST 2012 до конца не реализована и сейчас находится в стадии доработки?

**Comment by garex** [comment]
Ога.
__________________
Alexander Ustimenko
    +7 (952) 918-02-20


пн, 28 сент. 2020 г. в 13:36, MediaTen <notifications@github.com>:

**Comment by garex** [comment]
Всё починено в релизе 1.4

**Comment by mkukushkin35** [comment]
Здравствуйте. Не поделитесь ссылокой, как собрать php c поддержкой ГОСТ 2012? У вас в документации написно, что такой вариант существует, но ссылок, где можно посмотреть нет.

**Comment by garex** [comment]
Хз. Сами поищите или попробуйте. По идее надо собрать опенссл с гостом, а потом при сборке пхп подложить ему эту собранную либу как-то. Если найдете, то поделитесь здесь с нами.

**Comment by dimajolkin** [comment]
Добрый день. В через докере это можно добавить так.
FROM ....
FROM rnix/openssl-gost AS openssl-gost
COPY --from=openssl-gost /usr/local/ssl /usr/local/ssl
COPY --from=openssl-gost /usr/bin/openssl /usr/bin/openssl

использовать при этом new OpensslCli('/path/to/public/gost-esia.crt, '/path/to/gost-esia.key')

**Comment by garex** [comment]
@dimajolkin Эт не то. Тут имеется виду именно ПХП собрать и ОпенССЛ с гостом.

**Comment by mkukushkin35** [comment]
> Хз. Сами поищите или попробуйте. По идее надо собрать опенссл с гостом, а потом при сборке пхп подложить ему эту собранную либу как-то. Если найдете, то поделитесь здесь с нами.

В том то и дело, что ничего не нашел. А самому собирать, знаний не хватает. И если бы было просто, то какая нибудь информация бы была.

**Comment by mkukushkin35** [comment]
Еще вопрос.
При использовании сертификата с паролем, куда этот пароль ввести?
Пробую с openssl CLI.

**Comment by garex** [comment]
См. параметры и аргументы, которые принимаются внимательно.
__________________
Alexander Ustimenko
    +7 (952) 918-02-20


чт, 11 февр. 2021 г. в 17:57, mkukushkin35 <notifications@github.com>:

**Comment by mkukushkin35** [comment]
'signer' => new OpensslPkcs7('/path/to/public/certificate.cer', '/path/to/private.key'),
Вот ввод самих сертификатов.
Далее вводим только
'remoteSigner' => new OpenSslCliJwtSigner('/path/to/openssl'), 
А где пароль? 
Вроде все посмотрел еще раз внимательно

**Comment by garex** [comment]
Не внимательно.

См. конструктора.
__________________
Alexander Ustimenko
    +7 (952) 918-02-20


чт, 11 февр. 2021 г. в 18:26, mkukushkin35 <notifications@github.com>:

**Comment by mkukushkin35** [comment]
Разобрался, спасибо.
Теперь, после возврата на сайт - Access token can not be verified:
Как я понимаю, что то с ключами от ЕСИА.
Ключи скачал скриптом указал на ключ
'remoteCertificatePath' => EsiaProvider::RESOURCES.'esia.gost.prod.public.key',
Но почему то данная ошибка. Не подскажете в какую сторону покопать?

**Comment by mkukushkin35** [comment]
Я понял, ошибка появляется при верификации типа шифрования из приходящего $_GET['code'] и того, что проставляет система по умолчанию
$this->headers->get('alg') = RS256
$signer->getAlgorithmId() = GOST3410_2012_256
В общем решилось, при инициализвции класса, при получении ответа, заремить строку с openssl Cli.
Не плохо бы было прописать все это в описании применения. А то столько времени потерял, прежде чем разобрался.

**Comment by zorinalexey** [comment]
> 

Расскажи пожалуйста подробнее что и где нужно заменить. Тож емучаюсь с этими ключами
